[package]
name = "backend"
version = "0.1.0"
authors = ["muse254 <fanosoro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.2.8"
